/**
 * Recorded crowd lines. GENERATED by tools/make-voices.mjs — do not edit.
 *
 * Keyed by the line itself, so anything that has a recording plays it and
 * anything that does not falls back to the device voice. Run `npm run voices`
 * after changing or adding a line.
 */

export const VOICE_CLIPS: Record<string, number> = {
  "It's GOT to be the potato salad.": require('../../assets/voice/backyard-bbq--potato-salad.mp3'),
  "Something in that grill has gone WRONG.": require('../../assets/voice/backyard-bbq--grill.mp3'),
  "Dave. DAVE. Is that your shoes again?": require('../../assets/voice/backyard-bbq--uncles-shoes.mp3'),
  "Who put FISH in the trash?": require('../../assets/voice/backyard-bbq--trash-can.mp3'),
  "That pool water's been out here since MAY.": require('../../assets/voice/backyard-bbq--kiddie-pool.mp3'),
  "Oh my goodness, that cabbage smells gross!": require('../../assets/voice/fine-restaurant--cabbage-pot.mp3'),
  "Whooo weee, that's some strong cheese!": require('../../assets/voice/fine-restaurant--cheese-cart.mp3'),
  "Oh, who cut the onions? I'm crying over here!": require('../../assets/voice/fine-restaurant--onion-board.mp3'),
  "That is the truffle. That is a four hundred dollar smell.": require('../../assets/voice/fine-restaurant--truffle-plate.mp3'),
  "It's the fish special. It's always the fish special.": require('../../assets/voice/fine-restaurant--fish-plate.mp3'),
  "Chef! CHEF! Something has died in the walk-in!": require('../../assets/voice/fine-restaurant--kitchen-bin.mp3'),
  "Table four would like a word with the manager. About the air.": require('../../assets/voice/fine-restaurant--table-four.mp3'),
  "...do you smell that?": require('../../assets/voice/noticed-1.mp3'),
  "What is that?": require('../../assets/voice/noticed-2.mp3'),
  "Does anyone else smell that?": require('../../assets/voice/noticed-3.mp3'),
  "EVERYBODY OUT!": require('../../assets/voice/panic-1.mp3'),
  "OUT! OUT! OUT!": require('../../assets/voice/panic-2.mp3'),
  "I can taste it!": require('../../assets/voice/panic-3.mp3'),
  "It was the SKUNK!": require('../../assets/voice/caught-1.mp3'),
  "Got him!": require('../../assets/voice/caught-2.mp3'),
  "I knew it!": require('../../assets/voice/caught-3.mp3'),
  "...that's not it either.": require('../../assets/voice/decoy-1.mp3'),
  "...no, that is not it.": require('../../assets/voice/decoy-2.mp3'),
  "AH HA! It was the CAT!": require('../../assets/voice/decoy-cat.mp3'),
  "Awww, he's asleep.": require('../../assets/voice/animal-asleep-1.mp3'),
  "Oh no. He must be a Snoozalot.": require('../../assets/voice/animal-asleep-2.mp3'),
  "Not again!": require('../../assets/voice/animal-asleep-3.mp3'),
};

/** The recording for a line, if there is one. */
export function clipFor(text: string): number | undefined {
  return VOICE_CLIPS[text];
}
